"""
Briefing server to host HTML briefing pages.

Simple FastAPI server that serves generated briefing pages.
"""

import uvicorn
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles

BRIEFINGS_DIR = Path(__file__).parent / "pages"

app = FastAPI(
    title="Kairo Briefings",
    description="Meeting briefing pages generated by Kairo"
)


@app.get("/", response_class=HTMLResponse)
async def home():
    """Home page listing available briefings."""
    briefings = list(BRIEFINGS_DIR.glob("*.html"))
    
    items = []
    for b in sorted(briefings, key=lambda x: x.stat().st_mtime, reverse=True)[:20]:
        items.append(f'<li><a href="/briefing/{b.stem}">{b.stem}</a></li>')
    
    html = f'''
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kairo Briefings</title>
        <style>
            body {{ font-family: system-ui, sans-serif; max-width: 600px; margin: 2rem auto; padding: 1rem; }}
            h1 {{ color: #6366f1; }}
            a {{ color: #6366f1; }}
            li {{ margin: 0.5rem 0; }}
        </style>
    </head>
    <body>
        <h1>Kairo Briefings</h1>
        <p>Recent meeting briefings:</p>
        <ul>
            {"".join(items) if items else "<li>No briefings yet</li>"}
        </ul>
    </body>
    </html>
    '''
    return HTMLResponse(content=html)


@app.get("/briefing/{briefing_id}", response_class=HTMLResponse)
async def get_briefing(briefing_id: str):
    """Serve a specific briefing page."""
    # Sanitize the briefing_id to prevent path traversal
    safe_id = "".join(c for c in briefing_id if c.isalnum())
    file_path = BRIEFINGS_DIR / f"{safe_id}.html"
    
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Briefing not found")
    
    return FileResponse(file_path, media_type="text/html")


@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "ok"}


def run_server(host: str = "127.0.0.1", port: int = 8080):
    """Run the briefing server."""
    print(f"Starting Kairo Briefings server at http://{host}:{port}")
    uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    run_server()
